augment_column: ir_spectra

# Additional augmented data to add to training set
augment_data_path: null

# Augmentations to perform on augment_column
augmentations:
  smooth:
      sigmas: [0.75, 1.25]
  horizontal:
      n_augments: 4