repos:
  - repo: local
    hooks:
      - id: add-license-headers
        name: Add License Headers
        entry: licenseheaders -cy -d src/blm/ -o "AI4SD team" -t LICENSE.tmpl
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: Ruff linting
        entry: uv run ruff check .
        language: system
        pass_filenames: false