model_type: 'BART'
model_checkpoint_path: null
d_model: 512
num_layers: 6
num_heads: 8
d_feedforward: 2048
lr: 0.001
weight_decay: 0
activation: 'gelu'
max_seq_len: 2048
embedding_norm: True
schedule: 'cycle'
warm_up_steps: 8000
dropout: 0.1
pos_enc_procedure: 'standard'
pos_enc_strength: 1
batch_size: 128
cv_split: 0