# Additional augmented data to add to training set
augment_data_path: null

# Augmentations to perform on augment_column
augmentations:
  -
    augment_column: ir_spectra
    augment_fns:
      horizontal:
        n_augments: 2