# Additional augmented data to add to training set
augment_data_path: null

# Augmentations to perform on augment_column
augmentations:
  -
    augment_column: smiles
    augment_fns:
      smiles_aug:
        n_augments: 2