# Additional augmented data to add to training set
augment_data_path: null

# Augmentations to perform on augment_column
augmentations:
  -
    augment_column: ir_spectra
    augment_fns:
      smooth:
        sigmas: [0.75, 1.25]