# ------------------------------------------------------------------------------------------------
# Advanced cluster-specific options
#

# GDR support
#
roceGdrResName: "nvidia.com/roce_gdr" # <optional, default="nvidia.com/roce_gdr">
numRoceGdr: 2 # <optional, default=0> set to 2 to leverage GDR on Vela with GDR over RoCE
topologyFileConfigMap: topo-gdr-2vf-canary  # <optional, default=""> Name of configmap containining /var/run/nvidia-topologyd/virtualTopology.xml for the system e.g. topo-gdr-2vf-canary
ncclGdrEnvConfigMap: nccl-netwk-env-vars # <optional, default=""> Name of configmap containing NCCL networking environment variables for the system e.g. nccl-netwk-env-vars

# Multinic support
#
# Note: when GDR over RoCE is used/available, the RoCE multi-nic network instance
# should be specified here instead of the TCP multi-nic network instance.
#
# Existing instance names can be listed with `oc get multinicnetwork`.
#
multiNicNetworkName: multi-nic-network # multi-nic-cni-operator-ipvlanl3 # # <optional, default=""> Name of multi-NIC network, if one is available

# MCAD and Co-scheduler Backward compatibility
#
#    With the change of CRD in MCAD 1.30+, helm deployments using this tool adhere to the new changes. If you are using old versions of MCAD, set this value to 'true' to generate AppWrappers with the old CRD.
#
useOldMcadCrd: false
useOldCoschedulerCrd: true
