
model_type: 'T5ForConditionalGeneration'
model_name: 'google-t5/t5-small'
multimodal_norm: True

optimiser: adam
lr: 1e-4
weight_decay: 0
adam_beta1: 0.9
adam_beta2: 0.999

model_checkpoint_path: null
batch_size: 128
cv_split: 0